# -*- coding: utf-8 -*-

"""
    awsecommerceservice

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from awsecommerceservice.decorators import lazy_property
from awsecommerceservice.configuration import Configuration
from awsecommerceservice.controllers.awse_commerce_service_binding_controller import AWSECommerceServiceBindingController


class AwsecommerceserviceClient(object):

    config = Configuration

    @lazy_property
    def awse_commerce_service_binding(self):
        return AWSECommerceServiceBindingController()


