# -*- coding: utf-8 -*-

"""
    awsecommerceservice

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ActionEnum(object):

    """Implementation of the 'Action' enum.

    TODO: type enum description here.

    Attributes:
        MOVETOCART: TODO: type description here.
        SAVEFORLATER: TODO: type description here.

    """

    MOVETOCART = 'MoveToCart'

    SAVEFORLATER = 'SaveForLater'

