# -*- coding: utf-8 -*-

"""
    awsecommerceservice

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class AvailabilityEnum(object):

    """Implementation of the 'Availability' enum.

    TODO: type enum description here.

    Attributes:
        AVAILABLE: TODO: type description here.

    """

    AVAILABLE = 'Available'

